---
- name: install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~vagrant/.rbenv

- name: install rbenv plugins
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~vagrant/.rbenv/plugins/ruby-build

- name: set rbenv paths in .bashrc
  blockinfile:
    name: ~vagrant/.bashrc
    block: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
      export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"

- name: detect if Ruby 2.4.0 is already installed
  stat:
    path: ~vagrant/.rbenv/versions/2.4.0
  register: ruby_installed

- name: install Ruby 2.4.0
  shell: bash -lci 'rbenv install 2.4.0'
  when: ruby_installed.stat.isdir is not defined

- name: check current version of Ruby
  shell: bash -lci 'ruby -v'
  changed_when: false
  register: ruby_version

- name: use Ruby 2.4.0
  shell: bash -lci 'rbenv global 2.4.0'
  when: ruby_version.stdout.find('2.4.0') == -1
