---
- name: install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~vagrant/.rbenv

- name: install rbenv plugins
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~vagrant/.rbenv/plugins/ruby-build

- name: set rbenv paths in .bashrc
  blockinfile:
    name: ~vagrant/.bashrc
    block: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
      export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
