---
- name: Update apt cache
  become: yes
  become_user: root
  apt: update_cache=yes

- name: Install Ruby dependencies
  become: yes
  become_user: root
  apt: pkg={{ item }} state=installed
  with_items:
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - libffi-dev
    - nodejs