---
- name: Add GPG Key for installing Postgresql
  become: yes
  become_user: root
  apt_key: url={{ psql_url }}

- name: Add Postgresql repository
  become: yes
  become_user: root
  apt_repository:
    repo: '{{ psql_repo }}'
    state: present

- name: Install Postgresql
  become: yes
  become_user: root
  apt:
    pkg: '{{ item }}'
    state: latest
    force: yes
    update_cache: yes
  with_items:
    - postgresql-common
    - postgresql-contrib-{{ psql_version }}
    - libpq-dev

- name: Create User
  become: yes
  become_user: postgres
  command: createuser vagrant -s
